"use strict";

/*
 * =========================================================
 * KASANE TETRIS AUDIO SYSTEM
 * =========================================================
 *
 * Features:
 *
 * - UISFX integration
 * - Native Web Audio SFX fallback
 * - External MP3 background music
 * - GitHub-hosted CC0 music
 * - Independent music toggle
 * - Music pause / resume
 * - iOS / iPadOS audio unlock
 * - Sound setting integration
 * - Music setting integration
 * - Button micro-interactions
 * - Haptic feedback
 *
 * Music file:
 *
 * ./music/tertris.mp3
 *
 * IMPORTANT:
 *
 * The music is NOT generated by Web Audio.
 * The actual MP3 file is loaded from the repository.
 *
 * =========================================================
 */


import {
  CONFIG,
  SFX
} from "./config.js";


/*
 * =========================================================
 * AUDIO FILE
 * =========================================================
 */

const BGM_PATH =
  "./music/tertris.mp3";


/*
 * =========================================================
 * AUDIO VOLUME
 * =========================================================
 *
 * Prefer CONFIG values when available.
 * =========================================================
 */

const BGM_VOLUME =
  typeof CONFIG.BGM_VOLUME === "number"
    ? CONFIG.BGM_VOLUME
    : 0.18;


const SFX_VOLUME =
  typeof CONFIG.SFX_VOLUME === "number"
    ? CONFIG.SFX_VOLUME
    : 0.42;


/*
 * =========================================================
 * AUDIO STATE
 * =========================================================
 */

let bgm =
  null;


let bgmStarted =
  false;


let bgmErrorShown =
  false;


let audioUnlocked =
  false;


/*
 * =========================================================
 * NATIVE WEB AUDIO
 * =========================================================
 */

let nativeAudioContext =
  null;


let nativeMasterGain =
  null;


/*
 * =========================================================
 * UISFX
 * =========================================================
 */

let uiSFX =
  null;


let sfxModulePromise =
  null;


let sfxLoading =
  false;


/*
 * =========================================================
 * SFX COOLDOWN
 * =========================================================
 */

const lastSfxAt =
  new Map();


/*
 * =========================================================
 * MUSIC SETTING
 * =========================================================
 */

function isMusicEnabled() {

  /*
   * Compatibility:
   *
   * Older save data may not contain
   * the music property.
   *
   * Missing music setting =
   * enabled.
   */

  return (
    window.KasaneData?.settings?.music !== false
  );

}


/*
 * =========================================================
 * GET GAME DATA
 * =========================================================
 *
 * Kasane's audio module should not depend
 * directly on app.js.
 *
 * The application can expose its data as:
 *
 * window.KasaneData
 *
 * If unavailable, use a safe local object.
 * =========================================================
 */

function getData() {

  if (
    window.KasaneData
  ) {

    return window.KasaneData;

  }


  /*
   * Compatibility fallback.
   */

  if (
    !window.KasaneAudioData
  ) {

    window.KasaneAudioData = {

      settings: {

        sound:
          true,

        music:
          true,

        haptic:
          true

      }

    };

  }


  return window.KasaneAudioData;

}


/*
 * =========================================================
 * GET SETTINGS
 * ========================================================= */

function getSettings() {

  const data =
    getData();


  if (
    !data.settings
  ) {

    data.settings = {};

  }


  if (
    typeof data.settings.sound !==
    "boolean"
  ) {

    data.settings.sound =
      true;

  }


  if (
    typeof data.settings.music !==
    "boolean"
  ) {

    data.settings.music =
      true;

  }


  if (
    typeof data.settings.haptic !==
    "boolean"
  ) {

    data.settings.haptic =
      true;

  }


  return data.settings;

}


/*
 * =========================================================
 * SAVE SETTINGS
 * =========================================================
 *
 * Kasane may already have its own storage
 * system. We intentionally avoid importing
 * storage.js here so audio.js remains independent.
 *
 * The application can provide:
 *
 * window.KasaneSaveSettings
 *
 * If it does not exist, localStorage is used.
 * ========================================================= */

function saveSettings() {

  const data =
    getData();


  if (
    typeof window.KasaneSaveSettings ===
    "function"
  ) {

    try {

      window.KasaneSaveSettings(
        data.settings
      );

      return;

    } catch {}

  }


  try {

    localStorage.setItem(
      "kasane-tetris-settings",
      JSON.stringify(
        data.settings
      )
    );

  } catch {}

}


/*
 * =========================================================
 * CREATE BGM
 * =========================================================
 */

function createBGM() {

  if (
    bgm
  ) {

    return bgm;

  }


  /*
   * Create a real HTMLAudioElement.
   *
   * This is intentionally NOT:
   *
   * new AudioContext()
   *
   * because the background music is an
   * actual MP3 file stored in GitHub.
   */

  bgm =
    new Audio(
      BGM_PATH
    );


  /*
   * Infinite loop.
   */

  bgm.loop =
    true;


  /*
   * Let the browser preload the file.
   */

  bgm.preload =
    "auto";


  /*
   * iOS / iPadOS.
   */

  bgm.setAttribute(
    "playsinline",
    ""
  );


  bgm.setAttribute(
    "webkit-playsinline",
    ""
  );


  /*
   * Background music volume.
   */

  bgm.volume =
    BGM_VOLUME;


  /*
   * Do not autoplay.
   *
   * Mobile browsers generally require
   * a user interaction first.
   */

  bgm.autoplay =
    false;


  /*
   * Music started.
   */

  bgm.addEventListener(
    "play",
    () => {

      bgmStarted =
        true;

    }
  );


  /*
   * Music paused.
   */

  bgm.addEventListener(
    "pause",
    () => {

      bgmStarted =
        false;

    }
  );


  /*
   * Music ended.
   *
   * Normally this should never happen
   * because loop=true.
   */

  bgm.addEventListener(
    "ended",
    () => {

      bgmStarted =
        false;

    }
  );


  /*
   * Loading error.
   */

  bgm.addEventListener(
    "error",
    () => {

      bgmStarted =
        false;


      if (
        bgmErrorShown
      ) {

        return;

      }


      bgmErrorShown =
        true;


      console.warn(
        "[Kasane] Background music failed to load:",
        BGM_PATH,
        bgm.error
      );

    }
  );


  return bgm;

}


/*
 * =========================================================
 * UNLOCK NATIVE AUDIO
 * =========================================================
 *
 * iOS / iPadOS Safari can suspend Web Audio
 * until a user interaction happens.
 * ========================================================= */

async function unlockNativeAudio() {

  const AudioContextClass =
    window.AudioContext ||
    window.webkitAudioContext;


  /*
   * Some browsers do not support
   * Web Audio.
   *
   * The HTMLAudioElement can still work.
   */

  if (
    !AudioContextClass
  ) {

    audioUnlocked =
      true;

    return true;

  }


  if (
    !nativeAudioContext
  ) {

    try {

      nativeAudioContext =
        new AudioContextClass();


      nativeMasterGain =
        nativeAudioContext.createGain();


      nativeMasterGain.gain.value =
        SFX_VOLUME;


      nativeMasterGain.connect(
        nativeAudioContext.destination
      );

    } catch (
      error
    ) {

      console.warn(
        "[Kasane] Web Audio initialization failed:",
        error
      );


      audioUnlocked =
        true;


      return true;

    }

  }


  try {

    if (
      nativeAudioContext.state ===
      "suspended"
    ) {

      await nativeAudioContext.resume();

    }


    /*
     * Tiny silent oscillator.
     *
     * This helps unlock audio on
     * Safari / iOS / iPadOS.
     */

    const oscillator =
      nativeAudioContext.createOscillator();


    const gain =
      nativeAudioContext.createGain();


    gain.gain.value =
      0;


    oscillator.connect(
      gain
    );


    gain.connect(
      nativeAudioContext.destination
    );


    oscillator.start();


    oscillator.stop(
      nativeAudioContext.currentTime +
      0.01
    );


    audioUnlocked =
      true;


    return true;

  } catch (
    error
  ) {

    console.warn(
      "[Kasane] Audio unlock failed:",
      error
    );


    return false;

  }

}


/*
 * =========================================================
 * START MUSIC
 * =========================================================
 *
 * IMPORTANT:
 *
 * This function NEVER resets currentTime.
 *
 * Therefore:
 *
 * music ON
 *     ↓
 * play
 *
 * music OFF
 *     ↓
 * pause
 *
 * music ON
 *     ↓
 * resume from previous position
 *
 * =========================================================
 */

async function startMusic() {

  const settings =
    getSettings();


  if (
    !settings.sound
  ) {

    return false;

  }


  if (
    !settings.music
  ) {

    return false;

  }


  const music =
    createBGM();


  if (
    !music
  ) {

    return false;

  }


  /*
   * Keep the configured volume.
   */

  music.volume =
    BGM_VOLUME;


  /*
   * Already playing.
   */

  if (
    !music.paused
  ) {

    bgmStarted =
      true;

    return true;

  }


  /*
   * IMPORTANT:
   *
   * No:
   *
   * music.currentTime = 0;
   *
   * This preserves the position.
   */

  try {

    const promise =
      music.play();


    if (
      promise &&
      typeof promise.then ===
      "function"
    ) {

      await promise;

    }


    bgmStarted =
      true;


    return true;

  } catch (
    error
  ) {

    bgmStarted =
      false;


    /*
     * Autoplay restrictions are normal
     * before user interaction.
     */

    console.warn(
      "[Kasane] Background music playback was blocked until user interaction.",
      error
    );


    return false;

  }

}


/*
 * =========================================================
 * PAUSE MUSIC
 * =========================================================
 *
 * This is the music OFF behavior.
 *
 * It does NOT reset currentTime.
 * ========================================================= */

function pauseMusic() {

  if (
    !bgm
  ) {

    return;

  }


  try {

    bgm.pause();

  } catch (
    error
  ) {

    console.warn(
      "[Kasane] Failed to pause background music:",
      error
    );

  }


  bgmStarted =
    false;

}


/*
 * =========================================================
 * STOP MUSIC
 * =========================================================
 *
 * Kept as a compatibility API.
 *
 * In Kasane, stopMusic behaves like pauseMusic
 * so the music position is preserved.
 * ========================================================= */

function stopMusic() {

  pauseMusic();

}


/*
 * =========================================================
 * MUSIC VOLUME
 * ========================================================= */

function setMusicVolume(
  volume
) {

  const normalized =
    Math.max(
      0,
      Math.min(
        1,
        Number(volume) || 0
      )
    );


  if (
    bgm
  ) {

    bgm.volume =
      normalized;

  }

}


/*
 * =========================================================
 * LOAD UISFX
 * ========================================================= */

function loadUISFXModule() {

  if (
    !sfxModulePromise
  ) {

    /*
     * Kasane's shared UISFX module.
     *
     * This is the same shared audio technology
     * used by the Gomoku project.
     */

    sfxModulePromise =
      import(
        "../js/uisfx.js"
      );

  }


  return sfxModulePromise;

}


/*
 * =========================================================
 * LOAD UISFX
 * ========================================================= */

async function loadUISFX() {

  const settings =
    getSettings();


  if (
    uiSFX ||
    !settings.sound ||
    sfxLoading
  ) {

    return uiSFX;

  }


  sfxLoading =
    true;


  try {

    const module =
      await loadUISFXModule();


    const createUISFX =
      module.createUISFX ||
      module.default?.createUISFX;


    if (
      typeof createUISFX !==
      "function"
    ) {

      throw new Error(
        "createUISFX is unavailable."
      );

    }


    uiSFX =
      createUISFX({

        volume:
          SFX_VOLUME

      });


    return uiSFX;

  } catch (
    error
  ) {

    console.warn(
      "[Kasane] UISFX unavailable; using native Web Audio fallback.",
      error
    );


    uiSFX =
      null;


    return null;

  } finally {

    sfxLoading =
      false;

  }

}


/*
 * =========================================================
 * PUBLIC AUDIO UNLOCK
 * ========================================================= */

export async function unlockAudio() {

  const settings =
    getSettings();


  /*
   * Unlock Web Audio.
   */

  await unlockNativeAudio();


  /*
   * Create the MP3 element.
   */

  createBGM();


  /*
   * Load UISFX.

   * This can happen asynchronously.
   */

  if (
    settings.sound
  ) {

    loadUISFX();

  }


  /*
   * Start BGM if enabled.
   */

  if (
    settings.sound &&
    settings.music
  ) {

    await startMusic();

  }


  return uiSFX;

}


/*
 * =========================================================
 * NATIVE SFX
 * ========================================================= */

function nativeSFX(
  cue
) {

  const context =
    nativeAudioContext ||
    null;


  if (
    !context ||
    !nativeMasterGain ||
    !audioUnlocked
  ) {

    return;

  }


  const now =
    context.currentTime;


  const oscillator =
    context.createOscillator();


  const gain =
    context.createGain();


  let f1 =
    240;


  let f2 =
    280;


  let duration =
    0.055;


  let type =
    "sine";


  switch (
    cue
  ) {

    case SFX.move:

      f1 =
        210;

      f2 =
        270;

      duration =
        0.045;

      type =
        "sine";

      break;


    case SFX.rotate:

      f1 =
        320;

      f2 =
        430;

      duration =
        0.055;

      type =
        "sine";

      break;


    case SFX.hold:

      f1 =
        260;

      f2 =
        190;

      duration =
        0.075;

      type =
        "triangle";

      break;


    case SFX.drop:

      f1 =
        160;

      f2 =
        90;

      duration =
        0.08;

      type =
        "triangle";

      break;


    case SFX.lock:

      f1 =
        180;

      f2 =
        120;

      duration =
        0.055;

      type =
        "sine";

      break;


    case SFX.line:

      f1 =
        430;

      f2 =
        700;

      duration =
        0.12;

      type =
        "sine";

      break;


    case SFX.tetris:

      f1 =
        420;

      f2 =
        920;

      duration =
        0.25;

      type =
        "sine";

      break;


    case SFX.tSpin:

      f1 =
        280;

      f2 =
        820;

      duration =
        0.24;

      type =
        "triangle";

      break;


    case SFX.combo:

      f1 =
        500;

      f2 =
        800;

      duration =
        0.12;

      type =
        "sine";

      break;


    case SFX.level:

      f1 =
        350;

      f2 =
        700;

      duration =
        0.18;

      type =
        "sine";

      break;


    case SFX.gameover:

      f1 =
        220;

      f2 =
        80;

      duration =
        0.35;

      type =
        "triangle";

      break;


    case SFX.pause:

      f1 =
        260;

      f2 =
        180;

      duration =
        0.08;

      type =
        "sine";

      break;


    case SFX.resume:

      f1 =
        180;

      f2 =
        360;

      duration =
        0.08;

      type =
        "sine";

      break;


    default:

      f1 =
        240;

      f2 =
        280;

      duration =
        0.055;

      type =
        "sine";

  }


  oscillator.type =
    type;


  oscillator.frequency.setValueAtTime(
    f1,
    now
  );


  oscillator.frequency.exponentialRampToValueAtTime(
    Math.max(
      50,
      f2
    ),
    now +
    duration
  );


  gain.gain.setValueAtTime(
    0.0001,
    now
  );


  gain.gain.exponentialRampToValueAtTime(
    0.18,
    now +
    Math.min(
      0.012,
      duration *
      0.25
    )
  );


  gain.gain.exponentialRampToValueAtTime(
    0.0001,
    now +
    duration
  );


  oscillator.connect(
    gain
  );


  gain.connect(
    nativeMasterGain
  );


  oscillator.start(
    now
  );


  oscillator.stop(
    now +
    duration +
    0.01
  );

}


/*
 * =========================================================
 * PLAY SFX
 * ========================================================= */

export async function playSFX(
  cue,
  options = {}
) {

  const settings =
    getSettings();


  if (
    !settings.sound
  ) {

    return;

  }


  const now =
    performance.now();


  const cooldown =
    options.cooldownMs ??
    35;


  const last =
    lastSfxAt.get(
      cue
    ) ??
    -Infinity;


  if (
    now -
    last <
    cooldown
  ) {

    return;

  }


  lastSfxAt.set(
    cue,
    now
  );


  /*
   * Unlock audio on user interaction.
   */

  await unlockNativeAudio();


  /*
   * Start music independently.
   *
   * Music is not tied to the SFX system,
   * but the same interaction can unlock both.
   */

  if (
    settings.music
  ) {

    startMusic();

  }


  /*
   * Prefer UISFX.
   */

  const ui =
    uiSFX ||
    await loadUISFX();


  if (
    ui &&
    typeof ui.play ===
    "function"
  ) {

    try {

      ui.play(
        cue,
        {

          retrigger:
            options.retrigger ||
            "restart",

          cooldownMs:
            cooldown

        }
      );


      return;

    } catch (
      error
    ) {

      console.warn(
        `[Kasane] UISFX "${cue}" failed; using native fallback.`,
        error
      );

    }

  }


  /*
   * Native fallback.
   */

  nativeSFX(
    cue
  );

}


/*
 * =========================================================
 * SOUND ENABLE / DISABLE
 * ========================================================= */

export function setSoundEnabled(
  enabled
) {

  const settings =
    getSettings();


  settings.sound =
    Boolean(
      enabled
    );


  saveSettings();


  /*
   * Sound OFF:
   *
   * - stop SFX
   * - pause music
   *
   * Music position remains preserved.
   */

  if (
    !settings.sound
  ) {

    pauseMusic();


    if (
      uiSFX?.stopAll
    ) {

      try {

        uiSFX.stopAll();

      } catch {}

    }


    return;

  }


  /*
   * Sound ON:
   *
   * We do not force autoplay.
   *
   * The next user interaction unlocks
   * the audio system.
   */

  audioUnlocked =
    false;

}


/*
 * =========================================================
 * MUSIC ENABLE / DISABLE
 * =========================================================
 *
 * Music is independent from SFX.
 *
 * OFF:
 *   pause
 *
 * ON:
 *   resume
 *
 * currentTime is NEVER reset.
 * ========================================================= */

export function setMusicEnabled(
  enabled
) {

  const settings =
    getSettings();


  settings.music =
    Boolean(
      enabled
    );


  saveSettings();


  /*
   * MUSIC OFF
   */

  if (
    !settings.music
  ) {

    pauseMusic();

    return;

  }


  /*
   * MUSIC ON
   *
   * The toggle change itself is a user
   * interaction, so this is a valid place
   * to unlock and resume playback.
   */

  unlockAudio();

}


/*
 * =========================================================
 * BUTTON MICRO INTERACTIONS
 * ========================================================= */

export function decorateButtons() {

  document
    .querySelectorAll(
      "button"
    )
    .forEach(
      button => {

        button.classList.add(
          "gomoku-pressable"
        );


        if (
          button.dataset.kasaneAudioDecorated ===
          "1"
        ) {

          return;

        }


        button.dataset.kasaneAudioDecorated =
          "1";


        /*
         * PRESS
         */

        button.addEventListener(
          "pointerdown",
          () => {

            if (
              button.disabled
            ) {

              return;

            }


            unlockAudio();


            playSFX(
              SFX.move,
              {
                cooldownMs:
                  80
              }
            );

          },
          {
            passive:
              true
          }
        );


        /*
         * RELEASE
         */

        button.addEventListener(
          "pointerup",
          () => {

            if (
              button.disabled
            ) {

              return;

            }

          },
          {
            passive:
              true
          }
        );


        /*
         * CANCEL
         */

        button.addEventListener(
          "pointercancel",
          () => {

            if (
              button.disabled
            ) {

              return;

            }

          },
          {
            passive:
              true
          }
        );

      }
    );

}


/*
 * =========================================================
 * GLOBAL AUDIO UNLOCK
 * ========================================================= */

function installGlobalAudioUnlock() {

  const handler =
    () => {

      const settings =
        getSettings();


      if (
        !settings.sound
      ) {

        return;

      }


      unlockAudio();

    };


  document.addEventListener(
    "pointerdown",
    handler,
    {
      passive:
        true
    }
  );


  document.addEventListener(
    "touchstart",
    handler,
    {
      passive:
        true
    }
  );


  document.addEventListener(
    "keydown",
    handler,
    {
      passive:
        true
    }
  );

}


/*
 * =========================================================
 * MUSIC TOGGLE
 * ========================================================= */

function installMusicToggle() {

  const toggle =
    document.getElementById(
      "musicToggle"
    );


  if (
    !toggle
  ) {

    return;

  }


  /*
   * Sync UI.
   */

  toggle.checked =
    isMusicEnabled();


  if (
    toggle.dataset.musicBound ===
    "1"
  ) {

    return;

  }


  toggle.dataset.musicBound =
    "1";


  toggle.addEventListener(
    "change",
    () => {

      setMusicEnabled(
        toggle.checked
      );

    }
  );

}


/*
 * =========================================================
 * HAPTIC
 * ========================================================= */

export function haptic(
  amount = 8
) {

  const settings =
    getSettings();


  if (
    !settings.haptic
  ) {

    return;

  }


  if (
    "vibrate" in navigator
  ) {

    try {

      navigator.vibrate(
        amount
      );

    } catch {}

  }

}


/*
 * =========================================================
 * INITIALIZE
 * ========================================================= */

function initAudio() {

  /*
   * Prepare the MP3 element.
   */

  createBGM();


  /*
   * Prepare UI interactions.
   */

  decorateButtons();


  /*
   * Install mobile audio unlock.
   */

  installGlobalAudioUnlock();


  /*
   * Connect music toggle.
   */

  installMusicToggle();

}


/*
 * =========================================================
 * DOM READY
 * ========================================================= */

if (
  document.readyState ===
  "loading"
) {

  document.addEventListener(
    "DOMContentLoaded",
    initAudio,
    {
      once:
        true
    }
  );

} else {

  initAudio();

}


/*
 * =========================================================
 * GLOBAL API
 * =========================================================
 *
 * Other Kasane modules can use:
 *
 * window.KasaneAudio.startMusic()
 * window.KasaneAudio.pauseMusic()
 * window.KasaneAudio.setMusicEnabled(true)
 *
 * ========================================================= */

window.KasaneAudio = {

  /*
   * Start / resume music.
   */

  startMusic() {

    return startMusic();

  },


  /*
   * Pause without resetting position.
   */

  pauseMusic() {

    pauseMusic();

  },


  /*
   * Compatibility alias.
   */

  stopMusic() {

    stopMusic();

  },


  /*
   * Music setting.
   */

  setMusicEnabled(
    enabled
  ) {

    setMusicEnabled(
      enabled
    );

  },


  /*
   * Music volume.
   */

  setMusicVolume(
    volume
  ) {

    setMusicVolume(
      volume
    );

  },


  /*
   * SFX.

   */

  playSFX(
    cue,
    options
  ) {

    return playSFX(
      cue,
      options
    );

  },


  /*
   * Unlock audio.
   */

  unlockAudio() {

    return unlockAudio();

  },


  /*
   * Sound setting.
   */

  setSoundEnabled(
    enabled
  ) {

    setSoundEnabled(
      enabled
    );

  },


  /*
   * Haptic.
   */

  haptic(
    amount
  ) {

    haptic(
      amount
    );

  },


  /*
   * Return the actual HTMLAudioElement.
   */

  getMusicElement() {

    return bgm;

  },


  /*
   * Is music currently playing?
   */

  isMusicPlaying() {

    return Boolean(
      bgm &&
      !bgm.paused
    );

  },


  /*
   * Is music enabled?
   */

  isMusicEnabled() {

    return isMusicEnabled();

  }

};
